# Generated by Django 3.2.15 on 2022-10-19 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', default='', help_text='enter title of advertisement', max_length=200, verbose_name='Advertisement  title')),
                ('text', models.TextField(db_column='text_notice', help_text='enter text of advertisement', verbose_name='Advertisement text')),
                ('date', models.DateField(auto_now_add=True, db_column='date', verbose_name='Advertisement date')),
                ('author', models.ForeignKey(db_column='ad author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(db_column='response_text', help_text='enter text of response', max_length=200, verbose_name='Response text')),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='board.advertisement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
