# Generated by Django 3.2.15 on 2022-10-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('TH', 'Танки'), ('GL', 'Хилы'), ('DD', 'ДД'), ('MR', 'Торговцы'), ('QQ', 'Квестгиверы'), ('BM', 'Кузнецы'), ('LW', 'Кожевники'), ('PT', 'Зельевары'), ('SM', 'Мастера заклинаний')], db_column='ad category', default='TH', help_text='choose category of advertisement', max_length=2, verbose_name='Advertisement category'),
        ),
    ]
