# Generated by Django 3.2.15 on 2022-10-23 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_advertisement_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['date', 'title'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='response',
            new_name='message',
        ),
    ]
