# Generated by Django 3.2.15 on 2022-10-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20221023_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(db_column='reply ', help_text='enter text of reply', max_length=200, verbose_name='Reply text'),
        ),
    ]
