# Generated by Django 3.2.15 on 2022-10-26 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_reply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.DateField(auto_now_add=True, db_column='date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='is_accept',
            field=models.BooleanField(db_column='is accept', default=False, help_text='choose status reply', verbose_name='is accept'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(db_column='reply', help_text='enter text of reply', max_length=200, verbose_name='Reply text'),
        ),
    ]
